import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextAuthSessionProvider from "@/components/auth/SessionProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import "./globals.css";
import "../styles/dark-mode-fixes.css";
import { HeroHeader } from "@/components/ui/HeroHeader";
import { BackgroundBeams } from "@/components/ui/background-beams";
import { Footer } from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-gradient-to-white/20 from-white to-white/20  `}
      >
        <ThemeProvider>
          <NextAuthSessionProvider>
            <div className="flex flex-col h-full w-full">
              {children}
              {/* <Footer />   */}

            </div>
            {/* <BackgroundBeams /> */}
            <Toaster position="top-right" richColors closeButton />
          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
